sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t react-app -f Dockerfile.dev .

# react app test
# 결과를 상세히 보기 위한 --coverage
script:
 - docker run -e CI=true react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: react-app
  env: Reactapp-env
  bucket-name: elasticbeanstalk-us-east-2-035661480261
  bucket_path: react-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  